apiVersion: v1
kind: Service
metadata:
  name: phonebook-service
  labels: 
    name: phonebook-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetport: 80
      nodePort: 30001
  selector:
    name: phonebook-app-pod